export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

export const LOGOUT = 'LOGOUT';

export const ADD_CONTACT_START = 'ADD_CONTACT_START';
export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';
export const ADD_CONTACT_FAIL = 'ADD_CONTACT_FAIL';

export const FETCH_CONTACTS_START = 'FETCH_CONTACTS_START';
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS';
export const FETCH_CONTACTS_FAIL = 'FETCH_CONTACTS_FAIL';

export const DELETE_CONTACT = 'DELETE_CONTACT';

export const SET_CURRENT = 'SET_CURRENT';
export const DELETE_CURRENT = 'DELETE_CURRENT';

export const UPDATE_CONTACT = 'UPDATE_CONTACT';

export const FILTER_CONTACTS = 'FILTER_CONTACTS';



